package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/mschulkind/tillr/internal/config"
	"github.com/mschulkind/tillr/internal/db"
	"github.com/spf13/cobra"
)

var syncAgentsCmd = &cobra.Command{
	Use:   "sync-agents",
	Short: "Generate/update AGENTS.md with tillr-specific instructions",
	Long: `Generates or updates an AGENTS.md file in the project root with
tillr-specific instructions for AI agents.

The generated file includes:
  - Available tillr CLI commands
  - Current project status summary
  - Recommended workflow patterns
  - Feature state machine rules
  - Integration hooks

This command is also checked by 'tillr doctor'.`,
	Example: `  tillr sync-agents              # Generate/update AGENTS.md
  tillr sync-agents --json      # Output content as JSON instead of writing file`,
	RunE: func(cmd *cobra.Command, args []string) error {
		database, _, err := openDB()
		if err != nil {
			return err
		}
		defer database.Close() //nolint:errcheck

		p, err := db.GetProject(database)
		if err != nil {
			return err
		}

		// Gather project status
		counts, _ := db.FeatureCounts(database, p.ID)
		totalFeatures := 0
		for _, c := range counts {
			totalFeatures += c
		}

		// Build AGENTS.md content
		var b strings.Builder
		b.WriteString(fmt.Sprintf("# AGENTS.md - %s\n\n", p.Name))
		b.WriteString(fmt.Sprintf("*Auto-generated by `tillr sync-agents` on %s*\n\n", time.Now().Format("2006-01-02 15:04")))

		b.WriteString("## Project Management\n\n")
		b.WriteString("This project uses **tillr** for project management.\n")
		b.WriteString("All project data lives in a local SQLite database managed by the `tillr` CLI.\n\n")

		// Current status
		b.WriteString("## Current Project Status\n\n")
		b.WriteString(fmt.Sprintf("- **Project:** %s\n", p.Name))
		b.WriteString(fmt.Sprintf("- **Total Features:** %d\n", totalFeatures))
		for status, count := range counts {
			if count > 0 {
				label := strings.ReplaceAll(status, "-", " ")
			if len(label) > 0 {
				label = strings.ToUpper(label[:1]) + label[1:]
			}
			b.WriteString(fmt.Sprintf("- **%s:** %d\n", label, count))
			}
		}
		b.WriteString("\n")

		// Available commands
		b.WriteString("## Available Commands\n\n")
		b.WriteString("### Agent Workflow (Primary)\n\n")
		b.WriteString("```bash\n")
		b.WriteString("tillr next --json              # Get next work item with full context\n")
		b.WriteString("tillr done --result \"...\"       # Complete current work\n")
		b.WriteString("tillr fail --reason \"...\"       # Report failure\n")
		b.WriteString("tillr heartbeat --message \"...\" # Signal progress\n")
		b.WriteString("```\n\n")

		b.WriteString("### Feature Management\n\n")
		b.WriteString("```bash\n")
		b.WriteString("tillr feature list --json       # List all features\n")
		b.WriteString("tillr feature show <id> --json  # Feature details with spec\n")
		b.WriteString("tillr feature add \"Name\"        # Create a feature\n")
		b.WriteString("tillr feature edit <id> --status <status>  # Update status\n")
		b.WriteString("```\n\n")

		b.WriteString("### Idea Queue\n\n")
		b.WriteString("```bash\n")
		b.WriteString("tillr idea submit \"Title\" --description \"...\"  # Submit idea\n")
		b.WriteString("tillr idea process              # Auto-process pending ideas\n")
		b.WriteString("tillr idea list --json           # List all ideas\n")
		b.WriteString("```\n\n")

		b.WriteString("### Iteration Cycles\n\n")
		b.WriteString("```bash\n")
		b.WriteString("tillr cycle start <type> <feature-id>  # Start a cycle\n")
		b.WriteString("tillr cycle status               # View active cycles\n")
		b.WriteString("```\n\n")

		b.WriteString("### Collaboration\n\n")
		b.WriteString("```bash\n")
		b.WriteString("tillr discuss new \"Title\"        # Start RFC discussion\n")
		b.WriteString("tillr discuss comment <id>       # Add comment\n")
		b.WriteString("tillr search \"query\" --json      # Full-text search\n")
		b.WriteString("```\n\n")

		b.WriteString("### Other Useful Commands\n\n")
		b.WriteString("```bash\n")
		b.WriteString("tillr status --json              # Project overview\n")
		b.WriteString("tillr history --json             # Event history\n")
		b.WriteString("tillr qa pending --json          # Features awaiting QA\n")
		b.WriteString("tillr queue list --json          # Work queue\n")
		b.WriteString("tillr roadmap show --json        # Roadmap items\n")
		b.WriteString("tillr hooks                      # Show integration hooks\n")
		b.WriteString("tillr api docs                   # API documentation\n")
		b.WriteString("```\n\n")

		// Workflow patterns
		b.WriteString("## Workflow Patterns\n\n")
		b.WriteString("### Standard Agent Loop\n\n")
		b.WriteString("1. Run `tillr next --json` to get assigned work\n")
		b.WriteString("2. Read the `agent_guidance` field for instructions\n")
		b.WriteString("3. Implement the task\n")
		b.WriteString("4. Run `tillr done --result \"description of what was done\"`\n")
		b.WriteString("5. Repeat from step 1\n\n")

		b.WriteString("### Feature State Machine\n\n")
		b.WriteString("Features follow this state machine (all transitions must be valid):\n\n")
		b.WriteString("```\n")
		b.WriteString("draft -> planning -> implementing -> agent-qa -> human-qa -> done\n")
		b.WriteString("                                                     |\n")
		b.WriteString("                                                     v\n")
		b.WriteString("Any state can transition to 'blocked' and back.\n")
		b.WriteString("Features MUST go through human-qa before reaching done.\n")
		b.WriteString("```\n\n")

		b.WriteString("### Environment Variables\n\n")
		b.WriteString("```bash\n")
		b.WriteString("LIFECYCLE_AGENT_ID=\"my-agent\"  # Stable agent identifier\n")
		b.WriteString("```\n\n")

		b.WriteString("## Important Rules\n\n")
		b.WriteString("- Always use `--json` flag when consuming output programmatically\n")
		b.WriteString("- Send heartbeats during long-running tasks to prevent stale detection\n")
		b.WriteString("- Features must go through `human-qa` before being marked `done`\n")
		b.WriteString("- Use `tillr search` to find relevant context before starting work\n")
		b.WriteString("- Check `tillr feature show <id> --json` for specs before implementing\n")

		content := b.String()

		if jsonOutput {
			return printJSON(map[string]string{
				"content":  content,
				"filename": "AGENTS.md",
			})
		}

		// Write to project root (the directory containing .tillr.json)
		projectRoot, err := config.FindProjectRoot()
		if err != nil {
			return fmt.Errorf("finding project root: %w", err)
		}
		agentsPath := filepath.Join(projectRoot, "AGENTS.md")

		if err := os.WriteFile(agentsPath, []byte(content), 0o644); err != nil {
			return fmt.Errorf("writing AGENTS.md: %w", err)
		}

		fmt.Printf("Wrote AGENTS.md to %s\n", agentsPath)
		return nil
	},
}
