import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { getRetros } from '../api/client'

export function Retros() {
  const { data: retros, isLoading, error } = useQuery({
    queryKey: ['retros'],
    queryFn: getRetros,
  })

  return (
    <div className="max-w-3xl mx-auto">
      <h1 className="text-2xl font-semibold mb-2">Retros</h1>
      <p className="text-text-muted text-sm mb-4">
        Generated by <code className="px-1 rounded bg-bg-secondary">tillr retro</code>. Files live
        under <code className="px-1 rounded bg-bg-secondary">swarf/retros/</code>.
      </p>

      {isLoading && <div className="text-text-muted">Loading…</div>}
      {error && <div className="text-red-500">Error loading retros.</div>}

      {retros && retros.length === 0 && (
        <div className="text-text-muted text-sm">
          No retros yet. Run <code className="px-1 rounded bg-bg-secondary">tillr retro</code>.
        </div>
      )}

      {retros && retros.length > 0 && (
        <ul className="divide-y divide-border border border-border rounded-md">
          {retros.map((r) => (
            <li key={r.name} className="px-4 py-3 hover:bg-sidebar-hover">
              <Link to={`/retros/${encodeURIComponent(r.name)}`} className="flex items-center gap-3">
                <span className="font-mono text-sm flex-1">{r.name}</span>
                <span className="text-xs text-text-muted">
                  {(r.bytes / 1024).toFixed(1)}kb · {new Date(r.updated_at).toLocaleString()}
                </span>
              </Link>
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}
